version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - '5432:5432'
  java-app:
    build:
      context: .
    environment:
      - DB_URL=jdbc:postgresql://postgres_db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=mysecretpassword

    depends_on:
      - postgres

volumes:
  postgres-data:
    external: false